name: Activity
on:
    push:
        branches:
            - feature/*
    pull_request:
        types: [
            opened,
            reopened,
            synchronize,
            closed
        ]
    issues: 
        types: [opened, edited, closed]

jobs:
    checkout-test:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo $GITHUB_SHA
                echo $GITHUB_REF
            - uses: actions/checkout@v3
            - run: |
                echo "This is a test job for activity workflow"