name: Checkout Action
on: [push]
jobs:
    checkout-jobs:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Branch
              uses: actions/checkout@v2
            - name: List Files
              run: ls -a
            - name: List Files After
              run: ls -a  
    checkout-jobs-command:
        runs-on: ubuntu-latest
        steps:          
            - name: point to original branch
              run: |
                git init
                git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
                git fetch origin