name: Workflow Commands
on: [push]


jobs: 
    testing-wf-commands:
        runs-on: ubuntu-latest
        steps:
            - name: Run workflow commands
              run: |
                echo ":: error:: This is an error message"
                echo ":: warning:: This is a warning message"
                echo ":: notice:: This is a notice message"
                echo ":: debug:: This is a debug message"
                echo ":: error title:: File with error title text"